Algoritmo "ValoresParesregressivoate0"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/05/2021
Var
   Contador:Inteiro
   V: Inteiro


Inicio
      Escreval ("Digite um valor: ")
      Leia (V)
      Se (V % 2=1) entao
         V<- V -1
      FimSe
      Para Contador <- v até 0 passo -2 faca
           Escreval ( contador )
      FimPara

Fimalgoritmo